version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    environment:
      CI: "true"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-{{ arch }}
      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Set Up IOHook
          command: |
            mkdir -p node_modules\iohook\builds\electron-v80-win32-x64\build\Release\
            cp iohook\iohook.node node_modules\iohook\builds\electron-v80-win32-x64\build\Release\
            cp iohook\uiohook.dll node_modules\iohook\builds\electron-v80-win32-x64\build\Release\
      - run:
          name: Generate Dist
          shell: bash.exe
          command: |
            yarn run dist
            rm -rf dist/*.yaml
            rm -rf dist/main
            rm -rf dist/renderer
            rm -rf dist/win-unpacked
            rm -rf dist/.*
      - store_artifacts:
          path: dist
          destination: dist
