version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    environment:
      CI: "true"
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile
      - run:
          name: Set Up IOHook
          command: |
            if not exist "node_modules\iohook\builds\electron-v80-win32-x64\build\Release\" mkdir -p node_modules\iohook\builds\electron-v80-win32-x64\build\Release\
            cp iohook\iohook.node node_modules\iohook\builds\electron-v80-win32-x64\build\Release\
            cp iohook\uiohook.dll node_modules\iohook\builds\electron-v80-win32-x64\build\Release\
      - run: yarn run publish
      - store_artifacts:
          path: dist/win-unpacked
          destination: dist
