version: 2.1

orbs:
  win: circleci/windows@2.2.0

commands:
  build:
    parameters:
      cmd:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-{{ arch }}
      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Generate Dist
          command: |
            mkdir -p node_modules/memoryjs
            if [ ! -f node_modules/memoryjs/index.js ]; then
              echo "module.exports = {}" > node_modules/memoryjs/index.js
            fi
            yarn run << parameters.cmd >>
            rm -rf dist/*.yaml
            rm -rf dist/main
            rm -rf dist/renderer
            rm -rf dist/*-unpacked
      - store_artifacts:
          path: dist
          destination: dist

jobs:
  build-win:
    executor:
      name: win/default
      shell: bash.exe
    environment:
      CI: "true"
    steps:
      - build:
          cmd: dist:win
  build-win-sidecar:
    executor:
      name: win/default
      shell: bash.exe
    environment:
      CI: "true"
      ELECTRON_WEBPACK_APP_CREWLINK_SIDECAR: "1"
    steps:
      - build:
          cmd: dist:win
  build-osx-sidecar:
    macos:
      xcode: 11.3.0
    environment:
      CI: "true"
      ELECTRON_WEBPACK_APP_CREWLINK_SIDECAR: "1"
    steps:
      - build:
          cmd: dist:osx

workflows:
  version: 2.1
  build:
    jobs:
      - build-osx-sidecar
      - build-win
      - build-win-sidecar